import type { Font, PathCommand } from 'opentype.js';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { SVGLoader } from 'three/examples/jsm/loaders/SVGLoader.js';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import { segmentLine, type NeonSymbol } from './neon-symbols';

/**
 * Renders a neon sign in 3D: the customer's exact words, from the real font's letter outlines,
 * and line-art symbols, bent into glowing tubes in front of a wall. Nothing here is generated by
 * AI, so names are always spelled right; an AI picture can be used as the wall.
 */

export type WallId = 'brick' | 'concrete' | 'plaster' | 'wood' | 'dark';
export type Backboard = 'clear' | 'black' | 'none';
export type LineSize = 'lg' | 'md' | 'sm';

export interface NeonDesign {
  lines: { text: string; size: LineSize; color: string }[];
  /** Tube thickness, 0.5 (fine) to 2 (bold). */
  thickness: number;
  align: 'left' | 'center' | 'right';
  backboard: Backboard;
  /** A built-in wall, or a picture (data URL) to hang the sign on. */
  wall: WallId | { image: string };
}

export interface BuildReport {
  /** Characters the chosen font has no letter for, and emojis without a neon symbol. */
  skipped: string[];
  /** Nothing to draw: no words or symbols the sign can show. */
  empty: boolean;
}

const LINE_SIZES: Record<LineSize, number> = { lg: 100, md: 66, sm: 46 };
/** World units across the sign's longest side. */
const SIGN_SPAN = 10;
const WALL_Z = -0.75;

type Contour = { points: THREE.Vector2[]; closed: boolean };

export class NeonRenderer {
  private readonly renderer: THREE.WebGLRenderer;
  private readonly scene = new THREE.Scene();
  private readonly camera = new THREE.PerspectiveCamera(30, 1, 0.1, 200);
  private readonly controls: OrbitControls;
  private readonly composer: EffectComposer;
  private readonly bloom: UnrealBloomPass;
  private readonly sign = new THREE.Group();
  private readonly wallMaterial = new THREE.MeshStandardMaterial({ roughness: 0.92, metalness: 0 });
  private readonly wall: THREE.Mesh;
  private readonly glow: THREE.Mesh;
  /** Lights between the sign and the wall: the wash a real neon sign throws on the wall behind it. */
  private readonly lights = [0, 1, 2, 3, 4].map(() => new THREE.PointLight('#ffffff', 0, 0, 2));
  private wallKey = '';
  private frame = 0;
  private disposed = false;

  constructor(private readonly canvas: HTMLCanvasElement) {
    this.renderer = new THREE.WebGLRenderer({ canvas, antialias: true, preserveDrawingBuffer: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    // Neutral keeps the colour of bright tubes; ACES turns cyan and warm white to plain white.
    this.renderer.toneMapping = THREE.NeutralToneMapping;
    this.renderer.toneMappingExposure = 0.9;
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    this.renderer.outputColorSpace = THREE.SRGBColorSpace;

    this.scene.background = new THREE.Color('#050507');
    // A dim room, as in real neon photos, so the tubes carry the picture.
    this.scene.add(new THREE.HemisphereLight('#c9d2ff', '#1a1410', 0.32));
    const key = new THREE.DirectionalLight('#fff4e6', 0.22);
    key.position.set(-6, 8, 10);
    this.scene.add(key);

    this.wall = new THREE.Mesh(new THREE.PlaneGeometry(1, 1), this.wallMaterial);
    this.wall.position.z = WALL_Z;
    this.wall.receiveShadow = true;
    this.scene.add(this.wall);

    // The soft light the sign throws onto the wall around it.
    this.glow = new THREE.Mesh(
      new THREE.PlaneGeometry(1, 1),
      new THREE.MeshBasicMaterial({
        map: radialTexture(),
        transparent: true,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
        toneMapped: false,
      }),
    );
    this.glow.position.z = WALL_Z + 0.01;
    this.scene.add(this.glow);

    for (const light of this.lights) this.scene.add(light);
    this.scene.add(this.sign);

    this.composer = new EffectComposer(this.renderer);
    this.composer.addPass(new RenderPass(this.scene, this.camera));
    this.bloom = new UnrealBloomPass(new THREE.Vector2(512, 512), 0.85, 0.5, 0.5);
    this.composer.addPass(this.bloom);
    this.composer.addPass(new OutputPass());

    this.controls = new OrbitControls(this.camera, canvas);
    this.controls.enableDamping = true;
    this.controls.enablePan = false;
    this.controls.minAzimuthAngle = -0.55;
    this.controls.maxAzimuthAngle = 0.55;
    this.controls.minPolarAngle = Math.PI / 2 - 0.35;
    this.controls.maxPolarAngle = Math.PI / 2 + 0.25;
    this.controls.addEventListener('change', () => this.invalidate());
  }

  /** Builds the sign from the design and the font, replacing any earlier one. */
  async build(design: NeonDesign, font: Font): Promise<BuildReport> {
    const skipped = new Set<string>();
    const tubes = new Map<string, Contour[]>();
    const rows: { contours: { color: string; contour: Contour }[]; width: number; height: number }[] = [];

    for (const line of design.lines) {
      const size = LINE_SIZES[line.size];
      const { segments, unsupported } = segmentLine(line.text);
      for (const grapheme of unsupported) skipped.add(grapheme);
      const row: (typeof rows)[number] = { contours: [], width: 0, height: size };
      let x = 0;
      for (const segment of segments) {
        if (segment.kind === 'symbol') {
          const { contours, width } = symbolContours(
            segment.symbol!,
            size * 0.92,
            x + size * 0.06,
            -size * 0.78,
          );
          for (const contour of contours) row.contours.push({ color: line.color, contour });
          x += width + size * 0.18;
          continue;
        }
        // Whole letters (a Hindi syllable is several code points) are kept or left out together.
        const text = graphemes(segment.text)
          .filter((letter) => {
            if (letter === ' ' || [...letter].every((char) => font.charToGlyphIndex(char) > 0)) return true;
            skipped.add(letter);
            return false;
          })
          .join('');
        if (!text) continue;
        const path = font.getPath(text, x, 0, size, { kerning: true });
        for (const contour of commandsToContours(path.commands))
          row.contours.push({ color: line.color, contour });
        x += font.getAdvanceWidth(text, size, { kerning: true });
      }
      row.width = x;
      if (row.contours.length) rows.push(row);
    }

    this.clearSign();
    if (!rows.length) {
      this.invalidate();
      return { skipped: [...skipped], empty: true };
    }

    // Stack the rows, measure everything, then centre and scale to a fixed span.
    const gap = 0.32;
    let y = 0;
    const placed: { color: string; contour: Contour }[] = [];
    const widest = Math.max(...rows.map((row) => row.width));
    for (const row of rows) {
      y += row.height;
      const shift =
        design.align === 'left'
          ? 0
          : design.align === 'right'
            ? widest - row.width
            : (widest - row.width) / 2;
      for (const { color, contour } of row.contours) {
        placed.push({
          color,
          contour: {
            closed: contour.closed,
            points: contour.points.map((point) => new THREE.Vector2(point.x + shift, point.y + y)),
          },
        });
      }
      y += row.height * gap;
    }
    const box = new THREE.Box2();
    for (const { contour } of placed) for (const point of contour.points) box.expandByPoint(point);
    const size = box.getSize(new THREE.Vector2());
    const centre = box.getCenter(new THREE.Vector2());
    const scale = SIGN_SPAN / Math.max(size.x, size.y * 1.4);

    for (const { color, contour } of placed) {
      const points = contour.points.map(
        (point) => new THREE.Vector2((point.x - centre.x) * scale, -(point.y - centre.y) * scale),
      );
      const list = tubes.get(color) ?? [];
      list.push({ closed: contour.closed, points });
      tubes.set(color, list);
    }

    const width = size.x * scale;
    const height = size.y * scale;
    const radius = 0.055 * design.thickness;
    const colors: THREE.Color[] = [];
    for (const [hex, contours] of tubes) {
      const geometries = contours
        .map((contour) => tubeGeometry(contour, radius))
        .filter((g): g is THREE.TubeGeometry => !!g);
      if (!geometries.length) continue;
      const color = new THREE.Color(hex);
      colors.push(color);
      const merged = mergeGeometries(geometries);
      for (const geometry of geometries) geometry.dispose();
      // A coloured silicone sleeve that glows from inside: bright, slightly whiter at the core.
      const tube = new THREE.Mesh(
        merged,
        new THREE.MeshStandardMaterial({
          color: color.clone().lerp(new THREE.Color('#ffffff'), 0.08),
          emissive: color,
          // Bright colours (cyan, yellow, white) need less push than deep ones to look equally lit.
          emissiveIntensity: emissiveFor(color),
          roughness: 0.3,
          metalness: 0,
        }),
      );
      tube.castShadow = true;
      this.sign.add(tube);
    }

    if (design.backboard !== 'none') this.sign.add(backboardMesh(width, height, design.backboard));

    // Light the wall in the sign's own colour.
    const average = colors
      .reduce((sum, c) => sum.add(c), new THREE.Color(0, 0, 0))
      .multiplyScalar(1 / colors.length);
    this.lights.forEach((light, index) => {
      light.color.copy(average);
      light.intensity = (0.27 + width * 0.018) * (index === 0 || index === 4 ? 0.8 : 1);
      light.distance = Math.max(width, height) * 1.4 + 3;
      // Spread along the sign and kept well off the wall, so the wash is even rather than one hot spot.
      light.position.set((index - 2) * width * 0.22, 0, -0.26);
    });
    const glowMaterial = this.glow.material as THREE.MeshBasicMaterial;
    glowMaterial.color.copy(average).multiplyScalar(0.14);
    this.glow.scale.set(width * 1.9 + 3, height * 2.2 + 3, 1);

    this.wall.scale.set(Math.max(width, height) * 4 + 16, Math.max(width, height) * 4 + 16, 1);
    await this.setWall(design.wall);
    this.fit(width, height);
    this.invalidate();
    return { skipped: [...skipped], empty: false };
  }

  /** Matches the drawing size to the canvas's size on the page. */
  resize(width: number, height: number) {
    this.renderer.setSize(width, height, false);
    this.composer.setSize(width, height);
    this.camera.aspect = width / height;
    this.camera.updateProjectionMatrix();
    this.invalidate();
  }

  /** Renders a PNG with the longest side `longSide` pixels, then returns to the on-screen size. */
  async exportPng(longSide = 2400): Promise<Blob> {
    const size = this.renderer.getSize(new THREE.Vector2());
    const pixelRatio = this.renderer.getPixelRatio();
    const limit = this.renderer.capabilities.maxTextureSize;
    const target = Math.min(longSide, limit);
    const scale = target / Math.max(size.x, size.y);
    this.renderer.setPixelRatio(1);
    this.resize(Math.round(size.x * scale), Math.round(size.y * scale));
    this.composer.render();
    const blob = await new Promise<Blob | null>((resolve) => this.canvas.toBlob(resolve, 'image/png'));
    this.renderer.setPixelRatio(pixelRatio);
    this.resize(size.x, size.y);
    if (!blob) throw new Error('The picture could not be saved');
    return blob;
  }

  /** A JPEG data URL of the current view, for attaching to a quotation. */
  snapshot(maxSide = 1280): string {
    this.composer.render();
    const copy = document.createElement('canvas');
    const scale = Math.min(1, maxSide / Math.max(this.canvas.width, this.canvas.height));
    copy.width = Math.round(this.canvas.width * scale);
    copy.height = Math.round(this.canvas.height * scale);
    copy.getContext('2d')?.drawImage(this.canvas, 0, 0, copy.width, copy.height);
    return copy.toDataURL('image/jpeg', 0.86);
  }

  dispose() {
    this.disposed = true;
    cancelAnimationFrame(this.frame);
    this.controls.dispose();
    this.clearSign();
    this.wallMaterial.map?.dispose();
    this.composer.dispose();
    this.renderer.dispose();
  }

  private invalidate() {
    if (this.disposed || this.frame) return;
    this.frame = requestAnimationFrame(() => {
      this.frame = 0;
      const moving = this.controls.update();
      this.composer.render();
      if (moving) this.invalidate();
    });
  }

  private fit(width: number, height: number) {
    const fov = THREE.MathUtils.degToRad(this.camera.fov);
    const fitHeight = (height + 2.2) / 2 / Math.tan(fov / 2);
    const fitWidth = (width + 2.6) / 2 / Math.tan(fov / 2) / Math.max(this.camera.aspect, 0.4);
    const distance = Math.max(fitHeight, fitWidth, 6);
    this.camera.position.set(distance * 0.16, distance * 0.05, distance);
    this.controls.target.set(0, 0, 0);
    this.controls.minDistance = distance * 0.6;
    this.controls.maxDistance = distance * 1.6;
    this.controls.update();
  }

  private async setWall(wall: NeonDesign['wall']) {
    const key = typeof wall === 'string' ? wall : wall.image;
    if (key === this.wallKey) return;
    this.wallKey = key;
    const texture =
      typeof wall === 'string'
        ? wallTexture(wall)
        : await new THREE.TextureLoader().loadAsync(wall.image).catch(() => wallTexture('dark'));
    texture.colorSpace = THREE.SRGBColorSpace;
    if (typeof wall === 'string') {
      texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
      texture.repeat.set(3, 3);
    }
    this.wallMaterial.map?.dispose();
    this.wallMaterial.map = texture;
    // Pictures are shown brighter than textured walls, which are lit only by the sign and the room.
    this.wallMaterial.color.set(typeof wall === 'string' ? '#ffffff' : '#bdbdbd');
    this.wallMaterial.needsUpdate = true;
  }

  private clearSign() {
    for (const child of [...this.sign.children]) {
      this.sign.remove(child);
      child.traverse((node) => {
        if (node instanceof THREE.Mesh) {
          node.geometry.dispose();
          (Array.isArray(node.material) ? node.material : [node.material]).forEach((m: THREE.Material) =>
            m.dispose(),
          );
        }
      });
    }
  }
}

/** How hard a tube of this colour glows, so every colour reads as equally bright. */
export function emissiveFor(color: THREE.Color): number {
  const luminance = 0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b;
  // Aim every tube at the same glowing brightness, so the bloom treats all colours alike.
  return THREE.MathUtils.clamp(0.55 / Math.max(luminance, 0.05), 0.8, 3.2);
}

function graphemes(text: string): string[] {
  return typeof Intl !== 'undefined' && 'Segmenter' in Intl
    ? [...new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment(text)].map(
        (part) => part.segment,
      )
    : Array.from(text);
}

/** True when this browser can draw WebGL at all. */
export function webglAvailable(): boolean {
  try {
    const canvas = document.createElement('canvas');
    return Boolean(canvas.getContext('webgl2') ?? canvas.getContext('webgl'));
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------------------------

/** Turns opentype.js drawing commands (y down) into point lists, sampling the curves. */
export function commandsToContours(commands: PathCommand[]): Contour[] {
  const contours: Contour[] = [];
  let current: THREE.Vector2[] = [];
  let x = 0;
  let y = 0;
  const finish = (closed: boolean) => {
    if (current.length > 1) contours.push({ points: current, closed });
    current = [];
  };
  for (const command of commands) {
    switch (command.type) {
      case 'M':
        finish(false);
        x = command.x;
        y = command.y;
        current.push(new THREE.Vector2(x, y));
        break;
      case 'L':
        x = command.x;
        y = command.y;
        current.push(new THREE.Vector2(x, y));
        break;
      case 'Q': {
        const curve = new THREE.QuadraticBezierCurve(
          new THREE.Vector2(x, y),
          new THREE.Vector2(command.x1, command.y1),
          new THREE.Vector2(command.x, command.y),
        );
        current.push(...curve.getPoints(8).slice(1));
        x = command.x;
        y = command.y;
        break;
      }
      case 'C': {
        const curve = new THREE.CubicBezierCurve(
          new THREE.Vector2(x, y),
          new THREE.Vector2(command.x1, command.y1),
          new THREE.Vector2(command.x2, command.y2),
          new THREE.Vector2(command.x, command.y),
        );
        current.push(...curve.getPoints(10).slice(1));
        x = command.x;
        y = command.y;
        break;
      }
      case 'Z':
        finish(true);
        break;
    }
  }
  finish(false);
  return contours;
}

/**
 * A symbol's strokes, scaled so its 100-unit box is `height` tall, with its drawn left edge at x
 * and the box top at `top`. Returns the drawn width, for spacing what follows.
 */
function symbolContours(symbol: NeonSymbol, height: number, x: number, top: number) {
  const scale = height / 100;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg">${symbol.paths.map((d) => `<path d="${d}"/>`).join('')}</svg>`;
  const raw: Contour[] = [];
  for (const path of new SVGLoader().parse(svg).paths) {
    for (const sub of path.subPaths) {
      const points = sub.getPoints(24);
      if (points.length < 2) continue;
      const closed = points[0]!.distanceTo(points.at(-1)!) < 1;
      raw.push({ points: closed ? points.slice(0, -1) : points, closed });
    }
  }
  const xs = raw.flatMap((contour) => contour.points.map((point) => point.x));
  const left = Math.min(...xs);
  const right = Math.max(...xs);
  const contours = raw.map((contour) => ({
    closed: contour.closed,
    points: contour.points.map(
      (point) => new THREE.Vector2(x + (point.x - left) * scale, top + point.y * scale),
    ),
  }));
  return { contours, width: (right - left) * scale };
}

function tubeGeometry(contour: Contour, radius: number): THREE.TubeGeometry | null {
  const points: THREE.Vector3[] = [];
  for (const point of contour.points) {
    const last = points.at(-1);
    if (last && Math.hypot(last.x - point.x, last.y - point.y) < radius * 0.35) continue;
    points.push(new THREE.Vector3(point.x, point.y, 0));
  }
  if (contour.closed && points.length > 2 && points[0]!.distanceTo(points.at(-1)!) < radius * 0.35)
    points.pop();
  if (points.length < 2) return null;
  const curve = new THREE.CatmullRomCurve3(points, contour.closed && points.length > 2, 'centripetal', 0.5);
  const segments = Math.min(900, Math.max(24, Math.round(curve.getLength() / (radius * 0.6))));
  return new THREE.TubeGeometry(curve, segments, radius, 8, contour.closed && points.length > 2);
}

function backboardMesh(width: number, height: number, kind: Exclude<Backboard, 'none'>) {
  const pad = 0.55;
  const w = width + pad * 2;
  const h = height + pad * 2;
  const r = 0.35;
  const shape = new THREE.Shape();
  shape.moveTo(-w / 2 + r, -h / 2);
  shape.lineTo(w / 2 - r, -h / 2);
  shape.quadraticCurveTo(w / 2, -h / 2, w / 2, -h / 2 + r);
  shape.lineTo(w / 2, h / 2 - r);
  shape.quadraticCurveTo(w / 2, h / 2, w / 2 - r, h / 2);
  shape.lineTo(-w / 2 + r, h / 2);
  shape.quadraticCurveTo(-w / 2, h / 2, -w / 2, h / 2 - r);
  shape.lineTo(-w / 2, -h / 2 + r);
  shape.quadraticCurveTo(-w / 2, -h / 2, -w / 2 + r, -h / 2);

  const group = new THREE.Group();
  const board = new THREE.Mesh(
    new THREE.ExtrudeGeometry(shape, {
      depth: 0.08,
      bevelEnabled: true,
      bevelSize: 0.02,
      bevelThickness: 0.02,
      bevelSegments: 2,
    }),
    kind === 'clear'
      ? new THREE.MeshPhysicalMaterial({
          color: '#e8f4ff',
          transparent: true,
          opacity: 0.16,
          roughness: 0.05,
          clearcoat: 1,
          clearcoatRoughness: 0.05,
          // The wall lights sit behind the board; without this they show as a bright square on it.
          specularIntensity: 0,
          side: THREE.FrontSide,
          depthWrite: false,
        })
      : new THREE.MeshStandardMaterial({ color: '#0b0b0d', roughness: 0.35, metalness: 0.1 }),
  );
  board.position.z = -0.2;
  board.receiveShadow = true;
  group.add(board);

  // Brushed-steel standoffs holding the board off the wall.
  const steel = new THREE.MeshStandardMaterial({ color: '#c9ccd1', metalness: 0.9, roughness: 0.3 });
  for (const [sx, sy] of [
    [-1, -1],
    [1, -1],
    [-1, 1],
    [1, 1],
  ] as const) {
    const standoff = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.07, 0.62, 20), steel);
    standoff.rotation.x = Math.PI / 2;
    standoff.position.set(sx * (w / 2 - 0.22), sy * (h / 2 - 0.22), -0.38);
    standoff.castShadow = true;
    group.add(standoff);
  }
  return group;
}

function radialTexture(): THREE.CanvasTexture {
  const canvas = document.createElement('canvas');
  canvas.width = canvas.height = 256;
  const ctx = canvas.getContext('2d')!;
  const gradient = ctx.createRadialGradient(128, 128, 0, 128, 128, 128);
  gradient.addColorStop(0, 'rgba(255,255,255,0.9)');
  gradient.addColorStop(0.35, 'rgba(255,255,255,0.35)');
  gradient.addColorStop(1, 'rgba(255,255,255,0)');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, 256, 256);
  return new THREE.CanvasTexture(canvas);
}

/** Wall surfaces drawn in code: brick, concrete, plaster, wood panels and a dark matte wall. */
export function wallTexture(kind: WallId): THREE.CanvasTexture {
  const size = 512;
  const canvas = document.createElement('canvas');
  canvas.width = canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  let seed = 7;
  const random = () => {
    seed = (seed * 16807) % 2147483647;
    return seed / 2147483647;
  };
  const noise = (amount: number, alpha: number) => {
    for (let i = 0; i < amount; i++) {
      const shade = Math.floor(random() * 255);
      ctx.fillStyle = `rgba(${shade},${shade},${shade},${alpha})`;
      ctx.fillRect(random() * size, random() * size, 1 + random() * 2, 1 + random() * 2);
    }
  };

  if (kind === 'brick') {
    ctx.fillStyle = '#3a3633';
    ctx.fillRect(0, 0, size, size);
    const rows = 8;
    const h = size / rows;
    for (let row = 0; row < rows; row++) {
      for (let col = -1; col < 5; col++) {
        const x = col * (size / 4) + (row % 2 ? size / 8 : 0);
        const tone = 70 + random() * 40;
        ctx.fillStyle = `rgb(${tone + 40},${tone * 0.55},${tone * 0.45})`;
        ctx.fillRect(x + 3, row * h + 3, size / 4 - 6, h - 6);
      }
    }
    noise(9000, 0.08);
  } else if (kind === 'concrete') {
    ctx.fillStyle = '#7d7d7a';
    ctx.fillRect(0, 0, size, size);
    for (let i = 0; i < 60; i++) {
      const shade = 100 + random() * 50;
      ctx.fillStyle = `rgba(${shade},${shade},${shade - 4},0.12)`;
      ctx.beginPath();
      ctx.arc(random() * size, random() * size, 20 + random() * 80, 0, Math.PI * 2);
      ctx.fill();
    }
    noise(14000, 0.1);
  } else if (kind === 'plaster') {
    ctx.fillStyle = '#e9e4dc';
    ctx.fillRect(0, 0, size, size);
    noise(12000, 0.05);
  } else if (kind === 'wood') {
    for (let plank = 0; plank < 6; plank++) {
      const tone = 90 + random() * 30;
      ctx.fillStyle = `rgb(${tone + 30},${tone * 0.7},${tone * 0.45})`;
      ctx.fillRect(plank * (size / 6), 0, size / 6, size);
      ctx.strokeStyle = 'rgba(40,24,12,0.35)';
      for (let line = 0; line < 9; line++) {
        ctx.beginPath();
        const x = plank * (size / 6) + random() * (size / 6);
        ctx.moveTo(x, 0);
        ctx.bezierCurveTo(x + 6, size / 3, x - 6, (size * 2) / 3, x + 3, size);
        ctx.stroke();
      }
      ctx.fillStyle = 'rgba(0,0,0,0.5)';
      ctx.fillRect(plank * (size / 6), 0, 2, size);
    }
    noise(6000, 0.05);
  } else {
    ctx.fillStyle = '#16161a';
    ctx.fillRect(0, 0, size, size);
    noise(9000, 0.05);
  }
  return new THREE.CanvasTexture(canvas);
}
